language: php

php:
  - "7.1"

integrations:
  hub:
    - integrationName: demo_aws
      region: us-east-1
      type: ecr

build:
  ci:
    - docker build -t 412520076220.dkr.ecr.us-east-1.amazonaws.com/lara:latest .
    - docker push 412520076220.dkr.ecr.us-east-1.amazonaws.com/lara:latest
  on_success:
    - shipctl put_resource_state_multi lara_img "versionName=latest buildNumber=$BUILD_NUMBER"

resources:
  # app service image
  - name: lara_img
    type: image
    integration: "demo_aws"
    versionTemplate:
      sourceName: "412520076220.dkr.ecr.us-east-1.amazonaws.com/lara"
      versionName: "latest"

  - name: app_params
    type: params
    version:
      params:
        PORT: 80
        ENVIRONMENT: "dev"

  - name: app_docker_opts
    type: dockerOptions
    versionTemplate:
      memory: 100
      portMappings:
        - 80:8080

  - name: app_replicas
    type: replicas
    version:
      count: 1

  - name: ecs_cluster
    type: cluster
    integration: demo_aws
    pointer:
      sourceName : "tbd"
      region: "tbd"

jobs:
  - name: e2eLaravel_runCI
    type: runCI
    steps:
      - TASK:
          script:
            - pwd
      - OUT: lara_img

  - name: app_manifest
    type: manifest
    steps:
     - IN: app_replicas
     - IN: app_docker_opts
     - IN: app_params
     - IN: lara_img

  - name: app_deploy
    type: deploy
    steps:
      - IN: app_manifest
      - IN: ecs_cluster
      - TASK: managed