resources:
# Automation scripts repo
  - name: code_repo
    type: gitRepo
    integration: "avinci_gh"
    versionTemplate:
      sourceName: "avinci/e2eLaravel"
      branch: master

# Terraform State
  - name: tf_state
    type: state

# Output of VPC provisioning
  - name: infra_info
    type: params
    versionTemplate:
      params:
        SEED: "initial_version"

# Output of Amazon RDS Postgres provisioning
  - name: rds_pg_info
    type: params
    versionTemplate:
      params:
        SEED: "initial_version"

jobs:
# Provision AWS VPC with Terraform
  - name: prov_vpc
    type: runSh
    integrations:
      - demo_aws
    steps:
      - IN: code_repo
      - IN: tf_state
      - TASK:
          name: provision
          runtime:
            options:
              env:
                - region: "us-east-1"
                - vpc_name: "vpc"
                - vpc_cidr_block: "10.10.0.0/16"
                - vpc_access_from_ip_range: "0.0.0.0/0"
                - vpc_public_subnet_1_cidr: "10.10.10.0/24"
                - vpc_public_subnet_2_cidr: "10.10.20.0/24"
                - ecs_cluster: "cluster"
                - ecs_key_pair_name: "demo-key"
                - max_instance_size: 3
                - min_instance_size: 1
                - desired_capacity: 2
                - ecs_instance_type: "t2.micro"
                - ecs_ami_id: "ami-fad25980"
                - postgres_db_name: "test_db"
                - postgres_db_username: "lara_admin"
                - postgres_db_password: "password!@#"
          script:
            - pushd $(shipctl get_resource_state "code_repo")/tf
            - export aws_access_key_id=$(shipctl get_integration_field "demo_aws" "accessKey")
            - export aws_secret_access_key=$(shipctl get_integration_field "demo_aws" "secretKey")
            - shipctl copy_file_from_resource_state "tf_state" terraform.tfstate . || true
            - shipctl replace "terraform.tfvars"
            - terraform init
            - terraform apply -auto-approve -var-file=terraform.tfvars
      - OUT: infra_info
        overwrite: true
      - OUT: tf_state
    on_success:
      script:
        - shipctl put_resource_state_multi infra_info "versionName=$vpc_name" "vpc_id=$(terraform output vpc_id)" "region=$region" "vpc_public_sg_id=$(terraform output vpc_public_sg_id)" "vpc_public_sn_1_id=$(terraform output vpc_public_sn_1_id)" "vpc_public_sn_2_id=$(terraform output vpc_public_sn_2_id)"
        - shipctl put_resource_state_multi infra_info "rds_engine=$(terraform output engine)" "rds_engine_version=$(terraform output engine_version)" "rds_endpoint=$(terraform output endpoint)"
        - shipctl put_resource_state_multi infra_info "rds_port=$(terraform output port)" "rds_db_name=$(terraform output db_name)" "rds_db_user=$(terraform output db_user)"
    always:
      script:
        - shipctl copy_file_to_resource_state terraform.tfstate tf_state
